# Generated by Django 5.2 on 2025-05-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="sentiment",
            field=models.IntegerField(
                choices=[
                    (0, "Very Negative"),
                    (1, "Negative"),
                    (2, "Neutral"),
                    (3, "Positive"),
                    (4, "Very Positive"),
                ],
                default=2,
            ),
        ),
    ]
