MEANINGFUL_COMMENTS = {
    0: [  # Very Negative
        "This makes me feel really uneasy.",
        "I don't like this at all.",
        "Why would someone post this?",
        "This is quite disturbing.",
        "Extremely upsetting image.",
        "Totally ruined my mood.",
        "This is the worst thing I’ve seen today.",
        "There’s nothing redeeming here.",
        "Makes me feel angry.",
        "Very disappointing post.",
        "How could someone even share this?",
        "Deeply uncomfortable to look at.",
        "I'm honestly disgusted.",
        "So dark and depressing.",
        "Just awful.",
        "Hard to look at this without cringing.",
        "Painful to even think about.",
        "I wish I hadn’t seen this.",
        "Seriously messed up.",
        "Completely inappropriate.",
        "Disturbing on so many levels.",
    ],
    1: [  # Negative
        "Not a fan of this post.",
        "Seems off to me.",
        "Could've been better.",
        "Doesn't really appeal to me.",
        "I'm not sure I like this.",
        "The vibe is off.",
        "Doesn't feel right.",
        "This isn't very good.",
        "Too much negativity in this.",
        "Feels poorly thought out.",
        "Not impressed.",
        "Kind of a letdown.",
        "Mediocre at best.",
        "Missed the mark.",
        "Not the quality I expected.",
        "Doesn’t feel genuine.",
        "Something about this bugs me.",
        "Feels lazy or rushed.",
        "Didn’t enjoy this at all.",
        "Could be triggering for some.",
        "Lacking meaning or depth.",
    ],
    2: [  # Neutral
        "Interesting post.",
        "Not good, not bad. Just okay.",
        "Hmm... I’m indifferent.",
        "Can’t decide how I feel about this.",
        "Just another post.",
        "Doesn't spark any strong feelings.",
        "Somewhat bland but not offensive.",
        "It’s fine, I guess.",
        "Neither here nor there.",
        "Unremarkable but acceptable.",
        "Okay post, nothing special.",
        "Standard stuff.",
        "Mildly engaging.",
        "Nothing to write home about.",
        "Could be worse, could be better.",
        "Doesn't stand out.",
        "I don't have much to say about this.",
        "Average content.",
        "Neutral impression overall.",
        "Might appeal to others more than me.",
        "I see what they’re going for, I think.",
    ],
    3: [  # Positive
        "This looks great!",
        "Nice post, I like it.",
        "This is quite uplifting!",
        "Good vibes here.",
        "Nicely done!",
        "Puts a smile on my face.",
        "Clean and well put together.",
        "There’s something really likable here.",
        "A joy to come across this.",
        "Solid content!",
        "Looks pretty cool!",
        "Neat post!",
        "This made me nod in approval.",
        "Genuinely good stuff.",
        "Enjoyed this a lot.",
        "Feels honest and thoughtful.",
        "I appreciate the effort.",
        "This has a warm energy.",
        "Good message overall.",
        "Pleasant and easy on the eyes.",
        "This resonates with me.",
    ],
    4: [  # Very Positive
        "Absolutely amazing!",
        "I love everything about this!",
        "So beautiful and touching!",
        "This made my day!",
        "Pure joy in one image!",
        "Perfection!",
        "This is inspiring beyond words.",
        "So wholesome!",
        "Overflowing with positivity!",
        "This should go viral!",
        "I can't stop smiling!",
        "Simply stunning!",
        "Beyond brilliant!",
        "Masterpiece!",
        "Instant favorite.",
        "Deserves all the praise.",
        "Heartwarming in every way.",
        "Just wow!",
        "Exceptional content!",
        "This post radiates love!",
        "One of the best things I've seen online!",
    ],
}
